### ISSUE TITLE
Ambiguous import statement

### ISSUE THREAD

**Issue by vaneuk** [netascode/nac-validate#2]
When I clone the repo and run `python iac_validate/__main__.py ` the following error appears:
```
Traceback (most recent call last):
  File "/<path_omitted>/iac-validate/iac_validate/__main__.py", line 5, in <module>
    import iac_validate.cli.main
  File "/<path_omitted>/iac-validate/iac_validate/cli/main.py", line 12, in <module>
    import iac_validate.validator
  File "/<path_omitted>/iac-validate/iac_validate/validator.py", line 22, in <module>
    class VaultTag(yaml.YAMLObject):
AttributeError: module 'yaml' has no attribute 'YAMLObject'
```
This is because following import
https://github.com/netascode/iac-validate/blob/428df5f7d3c53e98db3f990998f27fde9a6170d2/iac_validate/validator.py#L15
is treated as import from `iac_validate/yaml.py` and not from `PyYAML` package. I think we should rename `iac_validate/yaml.py`.

**Comment by danischm** [comment]
Yes, or maybe move everything from `yaml.py` to `util.py`, what do you think?

**Comment by vaneuk** [comment]
> Yes, or maybe move everything from `yaml.py` to `util.py`, what do you think?

I agree.
